apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 703682678721.dkr.ecr.us-east-2.amazonaws.com/demo-frontend
  newName: 703682678721.dkr.ecr.us-east-2.amazonaws.com/demo-frontend
  newTag: c59f4a68
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
